-- Solution 1: Create admin user with a valid auth.users reference
-- This uses the actual ID that will be generated by Supabase Auth

-- Step 1: Create user in Supabase Dashboard first, then note the actual ID
-- Step 2: Use that actual ID instead of the hardcoded UUID

-- Alternative approach: Check if auth user already exists
SELECT id, email, created_at 
FROM auth.users 
WHERE email = 'support@celorisdesigns.com';