import express, { Request, Response } from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const PORT = 3000;

// Body parser with 50MB limit to handle canvas image payloads
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// Health Check
app.get('/api/health', (_req: Request, res: Response) => {
  res.json({ status: 'ok', timestamp: Date.now() });
});

// AI Configuration Status Check
app.get('/api/ai/status', (_req: Request, res: Response) => {
  res.json({
    status: 'ok',
    hasApiKey: Boolean(process.env.GEMINI_API_KEY),
    model: 'gemini-3.1-flash-image-preview',
    capabilities: ['text-to-image', 'image-edit', 'image-variation'],
  });
});

// AI Image Generation & Editing Endpoint (Pro Plan Feature)
app.post('/api/ai/generate-image', async (req: Request, res: Response): Promise<void> => {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      res.status(400).json({
        success: false,
        error: 'Gemini API key is not configured. Please add GEMINI_API_KEY in the application Settings menu.',
      });
      return;
    }

    const { prompt, mode = 'create', imageBase64, mimeType = 'image/png', aspectRatio = '1:1' } = req.body;

    if (!prompt || typeof prompt !== 'string' || !prompt.trim()) {
      res.status(400).json({
        success: false,
        error: 'Please provide a valid text prompt for image generation or editing.',
      });
      return;
    }

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });

    const primaryModel = 'gemini-3.1-flash-image-preview';
    const fallbackModels = ['gemini-3.1-flash-image', 'gemini-2.5-flash-image'];

    // Helper to invoke generateContent with fallback models
    const executeCall = async (modelName: string) => {
      if (mode === 'edit' && imageBase64) {
        // Strip data: prefix if present
        let cleanData = imageBase64;
        let finalMime = mimeType;
        if (cleanData.startsWith('data:')) {
          const commaIdx = cleanData.indexOf(',');
          const header = cleanData.substring(0, commaIdx);
          const matchedMime = header.split(';')[0]?.replace('data:', '');
          if (matchedMime) finalMime = matchedMime;
          cleanData = cleanData.substring(commaIdx + 1);
        }

        return await ai.models.generateContent({
          model: modelName,
          contents: {
            parts: [
              {
                inlineData: {
                  data: cleanData,
                  mimeType: finalMime || 'image/png',
                },
              },
              {
                text: prompt,
              },
            ],
          },
        });
      } else {
        // Create mode (text-to-image)
        return await ai.models.generateContent({
          model: modelName,
          contents: {
            parts: [{ text: prompt }],
          },
          config: {
            imageConfig: {
              aspectRatio: aspectRatio || '1:1',
            },
          },
        });
      }
    };

    let response: any = null;
    let usedModel = primaryModel;

    try {
      response = await executeCall(primaryModel);
    } catch (primaryErr: any) {
      console.warn(`Primary model ${primaryModel} error, trying fallbacks:`, primaryErr?.message);
      let fallbackSuccess = false;
      for (const fallback of fallbackModels) {
        try {
          response = await executeCall(fallback);
          usedModel = fallback;
          fallbackSuccess = true;
          break;
        } catch (fbErr: any) {
          console.warn(`Fallback model ${fallback} error:`, fbErr?.message);
        }
      }
      if (!fallbackSuccess) {
        throw primaryErr;
      }
    }

    // Extract generated image
    let imageUrl: string | null = null;
    let textDescription = '';

    const candidates = response?.candidates || [];
    if (candidates.length > 0 && candidates[0].content?.parts) {
      for (const part of candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          const partMime = part.inlineData.mimeType || 'image/png';
          imageUrl = `data:${partMime};base64,${part.inlineData.data}`;
          break;
        } else if (part.text) {
          textDescription += part.text;
        }
      }
    }

    if (!imageUrl) {
      res.status(422).json({
        success: false,
        error: textDescription || 'No image data was generated by the model. Please adjust your prompt.',
        usedModel,
      });
      return;
    }

    res.json({
      success: true,
      imageUrl,
      usedModel,
      prompt,
      mode,
    });
  } catch (error: any) {
    console.error('Error generating image via Gemini API:', error);
    res.status(500).json({
      success: false,
      error: error?.message || 'Failed to process AI image generation request.',
    });
  }
});

// Vite middleware & Static server setup
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (_req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`PhotoLite Studio Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
