export const AI_MODELS = [
  'Deepseek v3.2',
  'Deepseek V4 Flash',
  'Devstral small 2',
  'Gemini 2.5 Flash Lite',
  'Gemma 4 26B A4B IT',
  'Glm 4.7 Flash',
  'Glm 4.7 FlashX',
  'Google Gemm 4 31B',
  'Google Gemm 4 26B A4B',
  'GPT OSS Safeguard 120B',
  'GPT-4.1 Nano',
  'GPT 5 nano',
  'Grok 4.1 fast reasoning',
  'Grok 4.1 fast  no reasoning',
  'Hy3',
  'kat Coder Air V2.5',
  'Laguna s 2.1',
  'Ling 3.0 Flash',
  'llama 4 Maverick 17B',
  'llama 4 Scout 17B',
  'Mercury 2',
  'Mercury Coder',
  'Minimax m2.7',
  'Ministral 14B',
  'Nemotron 3 Nano 30B',
  'nvideo nemotron 3 super',
  'Qwen 3 coder 30 B',
  'Qwen 3.5 flash',
  'Qwen 3.7 flash',
  'Qwen 3 235B a22b instruction',
  'Qwen 3 14 B',
  'Qwen 3 30 B',
  'stepfun 3.5 Flash',
  'Tencent HY-MT2-pro',
  'Tencent Hy3',
  'Trinity Large thinking',
];
